### ISSUE TITLE
[Info] Add EP or Boundary Value comments on test methods if applicable

### ISSUE THREAD

**Issue by tandeshao** [AY2122S2-CS2103T-T17-4/tp#127]
![image](https://user-images.githubusercontent.com/64015462/160068201-6fbd5291-c85e-4745-b54d-1a0bc87d7e9b.png)

**Comment by atmh** [comment]
Possible EPs for strings:
![image](https://user-images.githubusercontent.com/77260849/160069088-011755e9-5646-4dec-8db7-3cd6ccf7e066.png)
