### ISSUE TITLE
[PE-D] Tags with different casing allowed to be added

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S2-CS2103T-T17-4/tp#209]
The user guide states that tags added that already exist will be rejected. 

![image.png](https://raw.githubusercontent.com/ryanwalterlee/ped/main/files/0ca553aa-c700-4613-b02d-696f3b0902d9.png)

I tried to add a tag with the same spelling but different casing, but it was accepted (even though a regular user would assume that is the same)

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: ryanwalterlee/ped#5

**Comment by atmh** [comment]
Duplicate of #222
