### ISSUE TITLE
[PE-D] Numbers allowed to be added to tags

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S2-CS2103T-T17-4/tp#214]
![image.png](https://raw.githubusercontent.com/ryanwalterlee/ped/main/files/9d7eab7c-0884-4e35-a5d5-6418d2f29536.png)

Should '1' be allowed to be added as a tag? What does it mean?

-------------
Labels: `type.FeatureFlaw` `severity.Low`
original: ryanwalterlee/ped#6

**Comment by xpzmichael** [comment]
Numbers can be a valid tag.
