### ISSUE TITLE
Internal PE-D

### ISSUE THREAD

**Issue by atmh** [AY2122S2-CS2103T-T17-4/tp#254]
Simulate PE-D and report any findings here!

Best to follow a format like

```
## [<Docs/Bug/Flaw>-<specifics>-[additional detail]] <Descriptive one-liner of issue>

Severity: <High, Medium, Low, Very Low>

<Details such as steps to reproduce or screenshots>

[Suggestions]
```

<details>
<summary>Click here to view the examples</summary>

## [Docs-UG-Add] Invalid sample command for `add`. 

Severity: Very low

Sample command was missing one mandatory field. 

---

## [Bug-Find] Separator value does not work. 

Severity: Medium

Find command allows searching of values separated by commas, but the input does not seem to be separated. 

Steps to reproduce:
1. `find test, abc`
2. Returns an error message saying `unable to "test, abc"`. (can include screenshot)

Suggestion:
- Check if the user input that is parsed splits by commas, 
- otherwise update the UG and sample commands to indicate how values are separated.
</details>

Massive shout out to everyone who took part in this! ❤️

**Comment by pyk595** [comment]
[Flaw] Technically an integer

<img width="766" alt="image" src="https://user-images.githubusercontent.com/77255760/162554574-3b6b010f-c1b1-4ad4-a0ef-a0f65d63dde2.png">
<img width="384" alt="image" src="https://user-images.githubusercontent.com/77255760/162554583-5c115b71-afc3-45ec-8093-4f52b03b0955.png">
suggestion: Update in the ug stating that if the index exceeds a certain number you consider it an invalid format

**Comment by pyk595** [comment]
[Doc-CommandResult-message sequence] Sequence of messages is wrong
severity: Low
<img width="762" alt="image" src="https://user-images.githubusercontent.com/77255760/162554791-84f82149-95e1-4260-b1fe-30512333ba81.png">

Suggestion: description of command should come before parameter constraints

**Comment by pyk595** [comment]
[Doc-contact list-sequence] Contact list is not sorted alphabetically by name
severity: Low

You might get complaints that the contact list is not sorted alphabetically by name because that's how generic address books handle it.

Suggestion: Add in documentation that states that you are not sorting by name or if you are sorting by another metric

**Comment by atmh** [comment]
Fixed!
